[package]
name = "prisms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
boa_engine = "0.17.3"
proc-macro2 = "1.0.67"
quote = "1.0.33"
litrs = "0.4.0"
indoc = "2.0.4"